name: money2
version: 6.0.0-beta.1
homepage: https://money2.onepub.dev
documentation: https://money2.onepub.dev
description: Money and Currency classes with fixed precision maths, parsing and formatting. (Money.parse('$2010.00') * 10).format('S CC#,##0') -> $ US20,100
repository: https://github.com/onepub-dev/money.dart
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  decimal: ^3.0.0
  fixed: ^5.3.3
  intl: ^0.20.2
  meta: ^1.9.0
  strings: ^3.2.0
dev_dependencies:
  lint_hard: ^6.0.0
  test: ^1.17.10

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

